(rule
 (target delator_ppx_rewriter_selected.ml)
 (deps
  delator_ppx_rewriter_ox.ml
  delator_ppx_rewriter_stock.ml
  delator_ppx_rewriter_unified_stock.ml
  select-rewriter
  %{lib:ppxlib:META})
 (action
  (run
   ./select-rewriter
   %{ocaml-config:version}
   %{lib:ppxlib:META}
   %{target})))

(library
 (name delator_ppx)
 (public_name delator.ppx)
 (kind ppx_rewriter)
 (modules delator_ppx delator_ppx_rewriter_selected)
 (libraries ppxlib))
